import type { PresetComponent } from "./PresetPlayground";
import {
  ClassificationPreset,
  RegressionPreset,
  OverfitPreset,
  NeuronPreset,
} from "./simulations/wrapped";
import {
  KnnPreset,
  KMeansPreset,
  TreePreset,
  ForestPreset,
  SvmPreset,
  NaiveBayesPreset,
  MetricsPreset,
  BiasVariancePreset,
  CrossValPreset,
} from "./simulations/interactive";
import {
  PredictionGamePreset,
  DataReplayPreset,
  FeatureForgePreset,
  LabelLensPreset,
  ModelArenaPreset,
  PipelinePreset,
  DeploymentPreset,
  EthicsPreset,
} from "./simulations/concepts";

export const PRESET_IDS = [
  "prediction-game",
  "data-replay",
  "feature-forge",
  "label-lens",
  "regression-training",
  "train-test-split",
  "metrics-dashboard",
  "underfit-rigid",
  "overfit-dial",
  "bias-variance",
  "cross-validation",
  "knn-voronoi",
  "linear-regression",
  "logistic-boundary",
  "decision-tree",
  "random-forest",
  "naive-bayes",
  "svm-margin",
  "kmeans-cluster",
  "gradient-descent",
  "neural-network",
  "model-arena",
  "feature-engineering",
  "pipeline-blocks",
  "deployment-drift",
  "ethics-bubble",
] as const;

export type PresetId = (typeof PRESET_IDS)[number];

export const PRESET_REGISTRY: Record<
  PresetId,
  { component: PresetComponent; label: string }
> = {
  "prediction-game": { component: PredictionGamePreset, label: "Prediction Game" },
  "data-replay": { component: DataReplayPreset, label: "Data Replay" },
  "feature-forge": { component: FeatureForgePreset, label: "Feature Forge" },
  "label-lens": { component: LabelLensPreset, label: "Label Lens" },
  "regression-training": { component: RegressionPreset, label: "Training" },
  "train-test-split": { component: ClassificationPreset, label: "Train/Test" },
  "metrics-dashboard": { component: MetricsPreset, label: "Metrics" },
  "underfit-rigid": { component: ClassificationPreset, label: "Underfit" },
  "overfit-dial": { component: OverfitPreset, label: "Overfit" },
  "bias-variance": { component: BiasVariancePreset, label: "Bias/Variance" },
  "cross-validation": { component: CrossValPreset, label: "Cross Validation" },
  "knn-voronoi": { component: KnnPreset, label: "KNN" },
  "linear-regression": { component: RegressionPreset, label: "Linear Regression" },
  "logistic-boundary": { component: ClassificationPreset, label: "Logistic" },
  "decision-tree": { component: TreePreset, label: "Decision Tree" },
  "random-forest": { component: ForestPreset, label: "Random Forest" },
  "naive-bayes": { component: NaiveBayesPreset, label: "Naive Bayes" },
  "svm-margin": { component: SvmPreset, label: "SVM" },
  "kmeans-cluster": { component: KMeansPreset, label: "KMeans" },
  "gradient-descent": { component: RegressionPreset, label: "Gradient Descent" },
  "neural-network": { component: NeuronPreset, label: "Neural Network" },
  "model-arena": { component: ModelArenaPreset, label: "Model Arena" },
  "feature-engineering": { component: FeatureForgePreset, label: "Feature Engineering" },
  "pipeline-blocks": { component: PipelinePreset, label: "Pipeline" },
  "deployment-drift": { component: DeploymentPreset, label: "Deployment" },
  "ethics-bubble": { component: EthicsPreset, label: "Ethics" },
};

/** Maps lesson slug → preset id */
export const LESSON_PRESET_MAP: Record<string, PresetId> = {
  "prediction-game": "prediction-game",
  "data": "data-replay",
  "features": "feature-forge",
  "labels": "label-lens",
  "training": "regression-training",
  "testing": "train-test-split",
  "evaluation-metrics": "metrics-dashboard",
  "underfitting": "underfit-rigid",
  "overfitting": "overfit-dial",
  "bias-variance": "bias-variance",
  "cross-validation": "cross-validation",
  "knn": "knn-voronoi",
  "linear-regression": "linear-regression",
  "logistic-regression": "logistic-boundary",
  "decision-trees": "decision-tree",
  "random-forests": "random-forest",
  "naive-bayes": "naive-bayes",
  "svm": "svm-margin",
  "kmeans": "kmeans-cluster",
  "gradient-descent": "gradient-descent",
  "neural-networks": "neural-network",
  "model-selection": "model-arena",
  "feature-engineering": "feature-engineering",
  "pipelines": "pipeline-blocks",
  "deployment": "deployment-drift",
  "ethics": "ethics-bubble",
};
